CREATE TABLE public.central_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  url_company_page text,
  nome_da_empresa text,
  cnpj text,
  cnpj_raiz text,
  dominio text,
  nome_fantasia text,
  perfil_do_linkedin text,
  segmento text,
  cnae_principal_codigo bigint,
  cnae_principal text,
  tipo_de_estabelecimento text,
  porte_da_empresa text,
  total_de_funcionarios bigint,
  faixa_de_funcionarios text,
  faixa_de_faturamento text,
  total_de_filiais bigint,
  tipo_de_entidade text,
  natureza_juridica text,
  data_de_abertura date,
  nivel_de_atividade text,
  tendencia_de_crescimento text,
  telefone_principal text,
  demais_telefones text,
  endereco_completo text,
  tipo_de_logradouro text,
  logradouro text,
  numero text,
  cep text,
  bairro text,
  municipio text,
  uf text,
  email_principal text,
  demais_emails text,
  perfil_do_facebook text,
  perfil_do_instagram text,
  perfil_do_twitter text,
  situacao text,
  territorio text,
  trm text,
  faixa_score_propensao text,
  score_propensao text,
  faixa_score_contactability text,
  variacao_score_propensao text,
  possui_dividas_publicas text,
  divida_ativa_da_uniao text,
  fgts text,
  previdenciario text,
  valores_das_dividas_publicas text,
  saude_tributaria text,
  regime_tributario text,
  latitude text,
  longitude text,
  created_at timestamp with time zone DEFAULT now(),
  precisao_nivel text,
  cliente boolean null,
  produto text null,
  CONSTRAINT central_data_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  nome text,
  departamento text,
  nivel_acesso text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.tracking_equipe (
  user_id uuid NOT NULL,
  email text,
  nome text,
  latitude double precision,
  longitude double precision,
  ultimo_visto timestamp with time zone DEFAULT now(),
  CONSTRAINT tracking_equipe_pkey PRIMARY KEY (user_id),
  CONSTRAINT tracking_equipe_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.tracking_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  captured_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tracking_history_pkey PRIMARY KEY (id),
  CONSTRAINT tracking_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.extra_data_company (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_central_data uuid NOT NULL,
  nome text,
  telefone text,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT extra_data_company_pkey PRIMARY KEY (id),
  CONSTRAINT extra_data_company_id_central_data_fkey FOREIGN KEY (id_central_data) REFERENCES public.central_data(id)
);