// Opções de cadastro de empresa — espelhadas da versão Python (constantes.py)

const List<String> kDepartamentos = [
  'Agile',
  'Ataliba',
  'Costa & Gaudêncio',
  'D&S',
  'EcoPartner',
  'Elias Temer Júnior',
  'Field',
  'Gilberto Cardoso',
  'Grandes Contas',
  'Inside Sales',
  'Itamara',
  'Leandro Vinicius',
  'Mara Minatto Flores',
  'Marcelo Barros',
  'Milene Ferreira Fernandes',
];

const List<String> kRegimesTributarios = [
  'Simples Nacional',
  'Lucro Real',
  'Lucro Presumido',
  'MEI',
  'Imune do IRPJ',
  'Isenta do IRPJ',
  'Lucro Arbitrado',
  'Lucro Presumido/Arbitrado',
  'Lucro Presumido/Real',
  'Lucro Real/Arbitrado',
];

// key → label  (key é enviado ao webhook)
const Map<String, String> kPrioridades = {
  'high': 'Alta',
  'medium': 'Média',
  'low': 'Baixa',
};

const List<String> kProcuracoes = [
  'ALPHA COMEX',
  'CARDOSO',
  'CRISTIANO',
  'DSR',
  'D&S',
  'ELIANE',
  'GSH',
  'MORASTONI',
  'PRIMETAX CONSULTORIA',
  'PRIMETAX SOLUTIONS',
  'PRIME TAX',
  'RECUPERA-AI',
  'RECUPERA-C',
  'SAVE',
  'SAVE SOLUÇÕES',
  'SAVE TI',
  'SERGIO',
  'YURI',
];

const List<String> kValoresDivida = [
  'Não possui dívida',
  'Até R\$ 50 mil',
  'De R\$ 50 mil a R\$ 300 mil',
  'De R\$ 300 mil a R\$ 3 milhões',
  'De R\$ 3 milhões a R\$ 15 milhões',
  'Mais de R\$ 15 milhões',
];

const List<String> kAnalises = [
  'RT + Passivo',
  'RT',
  'Passivo',
  'Previdenciário',
];

// key → label em PT (key é o código HubSpot enviado ao webhook)
const Map<String, String> kSetores = {
  'ACCOUNTING': 'Contabilidade',
  'AIRLINES_AVIATION': 'Linhas aéreas/aviação',
  'ALTERNATIVE_DISPUTE_RESOLUTION': 'Resolução alternativa de disputas',
  'ALTERNATIVE_MEDICINE': 'Medicina alternativa',
  'ANIMATION': 'Animação',
  'APPAREL_FASHION': 'Vestuário e moda',
  'ARCHITECTURE_PLANNING': 'Arquitetura e planejamento',
  'ARTS_AND_CRAFTS': 'Artesanato',
  'AUTOMOTIVE': 'Automotivo',
  'AVIATION_AEROSPACE': 'Aviação e aeroespacial',
  'BANKING': 'Bancário',
  'BIOTECHNOLOGY': 'Biotecnologia',
  'BROADCAST_MEDIA': 'Meios de difusão',
  'BUILDING_MATERIALS': 'Materiais de construção',
  'BUSINESS_SUPPLIES_AND_EQUIPMENT': 'Suprimentos e equipamentos comerciais',
  'CAPITAL_MARKETS': 'Mercados de capitais',
  'CHEMICALS': 'Produtos químicos',
  'CIVIC_SOCIAL_ORGANIZATION': 'Organização cívica e social',
  'CIVIL_ENGINEERING': 'Engenharia civil',
  'COMMERCIAL_REAL_ESTATE': 'Imóveis comerciais',
  'COMPUTER_NETWORK_SECURITY': 'Segurança de redes e computadores',
  'COMPUTER_GAMES': 'Hardware de computador',
  'COMPUTER_NETWORKING': 'Redes de computadores',
  'COMPUTER_SOFTWARE': 'Software de computador',
  'INTERNET': 'Internet',
  'CONSTRUCTION': 'Construção',
  'CONSUMER_ELECTRONICS': 'Eletrônicos de consumo',
  'CONSUMER_GOODS': 'Bens de consumo',
  'CONSUMER_SERVICES': 'Serviços ao consumidor',
  'COSMETICS': 'Cosméticos',
  'DAIRY': 'Laticínios',
  'DEFENSE_SPACE': 'Defesa e espaço',
  'DESIGN': 'Projeto',
  'EDUCATION_MANAGEMENT': 'Gerenciamento educacional',
  'E_LEARNING': 'E-learning',
  'ELECTRICAL_ELECTRONIC_MANUFACTURING': 'Fabricação elétrica/eletrônica',
  'ENTERTAINMENT': 'Entretenimento',
  'ENVIRONMENTAL_SERVICES': 'Serviços ambientais',
  'EVENTS_SERVICES': 'Serviços para eventos',
  'EXECUTIVE_OFFICE': 'Escritório executivo',
  'FACILITIES_SERVICES': 'Serviços de instalações',
  'FARMING': 'Agricultura',
  'FINANCIAL_SERVICES': 'Serviços financeiros',
  'FINE_ART': 'Belas artes',
  'FISHERY': 'Pesca',
  'FOOD_BEVERAGES': 'Alimentos e bebidas',
  'FOOD_PRODUCTION': 'Produção de alimentos',
  'FUND_RAISING': 'Angariação de fundos',
  'FURNITURE': 'Mobília',
  'GAMBLING_CASINOS': 'Jogos de azar e cassinos',
  'GLASS_CERAMICS_CONCRETE': 'Vidro, cerâmica e concreto',
  'GOVERNMENT_ADMINISTRATION': 'Administração governamental',
  'GOVERNMENT_RELATIONS': 'Relações governamentais',
  'GRAPHIC_DESIGN': 'Design gráfico',
  'HEALTH_WELLNESS_AND_FITNESS': 'Saúde, bem-estar e fitness',
  'HIGHER_EDUCATION': 'Ensino superior',
  'HOSPITAL_HEALTH_CARE': 'Hospital e cuidados de saúde',
  'HOSPITALITY': 'Hotelaria',
  'HUMAN_RESOURCES': 'Recursos humanos',
  'IMPORT_AND_EXPORT': 'Importar e exportar',
  'INDIVIDUAL_FAMILY_SERVICES': 'Serviços individuais e familiares',
  'INDUSTRIAL_AUTOMATION': 'Automação industrial',
  'INFORMATION_SERVICES': 'Serviços de informação',
  'INFORMATION_TECHNOLOGY_AND_SERVICES': 'Tecnologia da informação e serviços',
  'INSURANCE': 'Seguro',
  'INTERNATIONAL_AFFAIRS': 'Assuntos internacionais',
  'INTERNATIONAL_TRADE_AND_DEVELOPMENT': 'Comércio internacional e desenvolvimento',
  'INVESTMENT_BANKING': 'Banco de investimento',
  'INVESTMENT_MANAGEMENT': 'Gestão de investimentos',
  'JUDICIARY': 'Judiciário',
  'LAW_ENFORCEMENT': 'Aplicação da lei',
  'LAW_PRACTICE': 'Prática de direito',
  'LEGAL_SERVICES': 'Serviços jurídicos',
  'LEGISLATIVE_OFFICE': 'Gabinete legislativo',
  'LEISURE_TRAVEL_TOURISM': 'Lazer, viagens e turismo',
  'LIBRARIES': 'Bibliotecas',
  'LOGISTICS_AND_SUPPLY_CHAIN': 'Logística e cadeia de suprimento',
  'LUXURY_GOODS_JEWELRY': 'Bens de luxo e joias',
  'MACHINERY': 'Maquinário',
  'MANAGEMENT_CONSULTING': 'Consultoria de gestão',
  'MARITIME': 'Marítimo',
  'MARKET_RESEARCH': 'Pesquisa de mercado',
  'MARKETING_AND_ADVERTISING': 'Marketing e publicidade',
  'MECHANICAL_OR_INDUSTRIAL_ENGINEERING': 'Engenharia mecânica ou industrial',
  'MEDIA_PRODUCTION': 'Produção de mídia',
  'MEDICAL_DEVICES': 'Dispositivos médicos',
  'MEDICAL_PRACTICE': 'Prática médica',
  'MENTAL_HEALTH_CARE': 'Cuidados de saúde mental',
  'MILITARY': 'Militar',
  'MINING_METALS': 'Mineração e metais',
  'MOTION_PICTURES_AND_FILM': 'Filmes e cinema',
  'MUSEUMS_AND_INSTITUTIONS': 'Museus e instituições',
  'MUSIC': 'Música',
  'NANOTECHNOLOGY': 'Nanotecnologia',
  'NEWSPAPERS': 'Jornais',
  'NON_PROFIT_ORGANIZATION_MANAGEMENT': 'Gestão de organizações sem fins lucrativos',
  'OIL_ENERGY': 'Petróleo e energia',
  'ONLINE_MEDIA': 'Mídia online',
  'OUTSOURCING_OFFSHORING': 'Subcontratação/externalização offshore',
  'PACKAGE_FREIGHT_DELIVERY': 'Entrega de pacotes/frete',
  'PACKAGING_AND_CONTAINERS': 'Embalagens e recipientes',
  'PAPER_FOREST_PRODUCTS': 'Papel e produtos florestais',
  'PERFORMING_ARTS': 'Artes cênicas',
  'PHARMACEUTICALS': 'Farmacêutica',
  'PHILANTHROPY': 'Filantropia',
  'PHOTOGRAPHY': 'Fotografia',
  'PLASTICS': 'Plásticos',
  'POLITICAL_ORGANIZATION': 'Organização política',
  'PRIMARY_SECONDARY_EDUCATION': 'Ensino primário/secundário',
  'PRINTING': 'Impressão',
  'PROFESSIONAL_TRAINING_COACHING': 'Treinamento profissional e coaching',
  'PROGRAM_DEVELOPMENT': 'Desenvolvimento de programas',
  'PUBLIC_POLICY': 'Políticas públicas',
  'PUBLIC_RELATIONS_AND_COMMUNICATIONS': 'Relações públicas e comunicações',
  'PUBLIC_SAFETY': 'Segurança pública',
  'PUBLISHING': 'Publicação',
  'RAILROAD_MANUFACTURE': 'Fabricação ferroviária',
  'RANCHING': 'Pecuária',
  'REAL_ESTATE': 'Imobiliária',
  'RECREATIONAL_FACILITIES_AND_SERVICES': 'Instalações e serviços recreativos',
  'RELIGIOUS_INSTITUTIONS': 'Instituições religiosas',
  'RENEWABLES_ENVIRONMENT': 'Renováveis e meio ambiente',
  'RESEARCH': 'Pesquisa',
  'RESTAURANTS': 'Restaurantes',
  'RETAIL': 'Varejo',
  'SECURITY_AND_INVESTIGATIONS': 'Segurança e investigações',
  'SEMICONDUCTORS': 'Semicondutores',
  'SHIPBUILDING': 'Construção naval',
  'SPORTING_GOODS': 'Artigos esportivos',
  'SPORTS': 'Esportes',
  'STAFFING_AND_RECRUITING': 'Pessoal e recrutamento',
  'SUPERMARKETS': 'Supermercados',
  'TELECOMMUNICATIONS': 'Telecomunicações',
  'TEXTILES': 'Têxteis',
  'THINK_TANKS': 'Grupos de reflexão',
  'TOBACCO': 'Tabaco',
  'TRANSLATION_AND_LOCALIZATION': 'Tradução e localização',
  'TRANSPORTATION_TRUCKING_RAILROAD': 'Transporte/caminhões/ferrovias',
  'UTILITIES': 'Serviços de utilidade pública',
  'VENTURE_CAPITAL_PRIVATE_EQUITY': 'Capital de risco e privado',
  'VETERINARY': 'Veterinária',
  'WAREHOUSING': 'Armazenamento',
  'WHOLESALE': 'Atacado',
  'WINE_AND_SPIRITS': 'Vinhos e bebidas alcoólicas',
  'WIRELESS': 'Sem fio',
  'WRITING_AND_EDITING': 'Redação e edição',
  'MOBILE_GAMES': 'Jogos para dispositivos móveis',
  'Cooperativa': 'Cooperativa',
  'Posto de combustível': 'Posto de combustível',
  'Distribuidor de mercadorias em geral': 'Distribuidor de mercadorias em geral',
  'Distribuidora de gás e combustíveis': 'Distribuidora de gás e combustíveis',
  'Perfumaria': 'Perfumaria',
  'Loja de Peças / Pneus': 'Loja de Peças / Pneus',
  'Produtor Rural (PF ou PJ)': 'Produtor Rural (PF ou PJ)',
  'Agroindústria': 'Agroindústria',
  'Indústria em geral': 'Indústria em geral',
  'Bar / Padaria / Pizzaria': 'Bar / Padaria / Pizzaria',
  'Profissional liberal (Médico, Engenheiro, etc.)': 'Profissional liberal (Médico, Engenheiro, etc.)',
  'Clínicas / Consultório': 'Clínicas / Consultório',
  'Agronegócio': 'Agronegócio',
  'Distribuidoras': 'Distribuidoras',
  'Café': 'Café',
  'Açougue': 'Açougue',
};
