// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGQyE8EToGb9JnVVbelBrQf2pRTUihpIg',
    appId: '1:194526953767:web:02a8a16665539a73532902',
    messagingSenderId: '194526953767',
    projectId: 'rumo-app-b05fe',
    authDomain: 'rumo-app-b05fe.firebaseapp.com',
    storageBucket: 'rumo-app-b05fe.firebasestorage.app',
    measurementId: 'G-9N2202P0JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ-IBTyRoxrY7TdUIc5gdmVpZcVYbMYCo',
    appId: '1:194526953767:android:d171cdb38632f6ea532902',
    messagingSenderId: '194526953767',
    projectId: 'rumo-app-b05fe',
    storageBucket: 'rumo-app-b05fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV9oPHVJyuDN1vtVecrdCQo62dfmGTetI',
    appId: '1:194526953767:ios:a948eb1e70f22629532902',
    messagingSenderId: '194526953767',
    projectId: 'rumo-app-b05fe',
    storageBucket: 'rumo-app-b05fe.firebasestorage.app',
    iosBundleId: 'com.rumo.dataRotaApp',
  );
}
